### ISSUE TITLE
House keys!

### ISSUE THREAD

**Issue by EveEnchooli** [fkk-cz/noire-public#161]
Giving/taking keys has not been working at the houses. It will say that it's giving or taking keys but doesn't remove/add them to the list. 
![image](https://user-images.githubusercontent.com/83321790/140252823-b2df290a-b5c0-4062-bd70-86f22352cfad.png)

**Comment by fkk-cz** [comment]
This was fixed in https://github.com/fkk-cz/noire/commit/f488d248ea2f86058ebe2667f6ed20c3280e6bf1

**Comment by EveEnchooli** [comment]
still wont let me take keys! still just says taking keys but doesn't fully take the keys
